#!/bin/bash
#http://stackoverflow.com/a/11301911/1705163

PYVERSION=2.7.7
VEVERSION=1.11.6

DEST=$(pwd)
if [ -n "$1" ]; then
    #does not require the dir to exist
    DEST=$(realpath "$1")
fi

#setup python
install_python() {
    pushd .
    local SRCDIR=$DEST/python/src
    local INSTALLDIR=$DEST/python/install
    mkdir -p ${SRCDIR} $INSTALLDIR
    if [[ -d ${SRCDIR}  && -d ${INSTALLDIR} ]]; then
        cd ${SRCDIR}
        local TARBALL=Python-${PYVERSION}.tgz
        curl -O https://www.python.org/ftp/python/${PYVERSION}/$TARBALL
        tar -zxvf $TARBALL
        cd Python-${PYVERSION}
        ./configure --prefix=${INSTALLDIR}
        make > /dev/null 2>&1
        make install > /dev/null 2>&1
        PYTHON=$INSTALLDIR/bin/python
    fi
    popd
}

#setup virtualenv
install_virtualenv() {
    pushd .
    local SRCDIR=$DEST/virtualenv/src
    local INSTALLDIR=${DEST}/virtualenv/install
    mkdir -p ${SRCDIR} ${INSTALLDIR}
    if [[ -d ${SRCDIR}  && -d ${INSTALLDIR} ]]; then
        cd ${SRCDIR}
        local TARBALL=virtualenv-${VEVERSION}.tar.gz
        curl -O https://pypi.python.org/packages/source/v/virtualenv/$TARBALL
        tar -zxvf $TARBALL
        cd virtualenv-${VEVERSION}
        if [ -v $PYTHON ]; then
            echo "no python: $PYTHON"
        else
            $PYTHON setup.py install
            virtualenv $INSTALLDIR -p $PYTHON
            source $INSTALLDIR/bin/activate
        fi
    fi
}

#TODO setup boto

#run the installation
echo "Installing Python..."
install_python
echo "Installing Virtualenv..."
install_virtualenv

