#!/bin/bash
#http://stackoverflow.com/a/11301911/1705163

PYVERSION=2.7.7
VEVERSION=1.11.6

DEST=$(pwd)
if [ -n "$1" ]; then
    #realpath does not require the dir to exist
    if hash realpath 2>/dev/null; then
        DEST=$(realpath "$1")
    else
        if [ "${1:0:1}" == "/" ]; then
            DEST=$1
        else
            DEST=$PWD/$1
        fi
    fi
fi

#setup python
install_python() {
    pushd .
    local SRCDIR=$DEST/python/src
    local INSTALLDIR=$DEST/python/install
    mkdir -p $SRCDIR $INSTALLDIR
    if [[ -d $SRCDIR  && -d $INSTALLDIR ]]; then
        cd $SRCDIR
        local TARBALL=Python-$PYVERSION.tgz
        curl -O https://www.python.org/ftp/python/$PYVERSION/$TARBALL
        tar -zxvf $TARBALL > /dev/null 2>&1
        cd Python-$PYVERSION
        ./configure --prefix=$INSTALLDIR > /dev/null 2>&1
        make > /dev/null 2>&1
        make install > /dev/null 2>&1
        PYTHON=$INSTALLDIR/bin/python
    fi
    popd
}

#setup virtualenv
install_virtualenv() {
    pushd .
    local SRCDIR=$DEST/virtualenv/src
    local INSTALLDIR=$DEST/virtualenv/install
    mkdir -p $SRCDIR $INSTALLDIR
    if [[ -d $SRCDIR  && -d $INSTALLDIR ]]; then
        cd $SRCDIR
        local TARBALL=virtualenv-$VEVERSION.tar.gz
        curl -O https://pypi.python.org/packages/source/v/virtualenv/$TARBALL
        tar -zxvf $TARBALL > /dev/null 2>&1
        cd virtualenv-$VEVERSION
        if [ -v PYTHON ]; then
            $PYTHON setup.py install > /dev/null 2>&1
            virtualenv $INSTALLDIR -p $PYTHON > /dev/null 2>&1
            #activate so that any python / pip runs in this python
            ACTIVATE=$DEST/activate
            ln -s $INSTALLDIR/bin/activate $ACTIVATE
            source $ACTIVATE
            echo $ACTIVATE
        else
            echo "no python: $PYTHON"
        fi
    fi
    popd
}

#run the installation
echo "Installing Python..."
install_python
echo "Installing Virtualenv..."
install_virtualenv
echo "installing boto..."
pip install boto

python -c "
import boto
print(boto.Version)
"

deactivate
